# Uses gunicorn with uvicorn workers.

runtime: python

# F1 = 2 workers (default), F2 = 4 workers
instance_class: F1

env: flex

# -w 2 sets uvicorn number of workers
# The number of workers you specify should match the
# instance class of your App Engine app.
entrypoint: gunicorn -b :$PORT -w 2 -k uvicorn.workers.UvicornWorker main:app

runtime_config:
    operating_system: "ubuntu22"
    runtime_version: "3.11"
